# Generated by Django 3.2.7 on 2021-09-07 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210903_1318'),
    ]

    operations = [
        # Step 1: Add a temporary UUID field
        migrations.AddField(
            model_name='cart',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # Step 2: Remove the old primary key
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        # Step 3: Rename uuid_id to id and make it primary key
        migrations.RenameField(
            model_name='cart',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
